### ISSUE TITLE
Trying to start Docker daemon

### ISSUE THREAD

**Issue by makamekm** [Max00355/Coffer#3]
Output: 
```
root@a301-9097-7434:/# dockerd
mkdir /var/lib/docker: permission denied
```

It tries to get the folder structure outside (but I am not root outside).

**Comment by f-prime** [comment]
You are trying to start Docker from within Coffer? This isn't something I have ever tried so I don't really know what would be going on here. If it's trying to get /var/lib/docker then that /var/lib/docker should be within the chroot. Do you think it's trying to access the /var/lib/docker that is outside of the chroot?

**Comment by makamekm** [comment]
Maybe it's because it tries to use set gid and uid, after rejection it writes this message. Almost the same error with sshd.

**Comment by f-prime** [comment]
Okay, so do you think this is a Coffer problem or a Docker problem, or just some kind of user error?

**Comment by makamekm** [comment]
I have solved this problem using udocker. But there is the error in fakeroot. You can try it by running "changeuser - user"
